/* Autogenerated by png2wx.pl on Tue Sep 11 19:10:37 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_srt_pi;

#endif /* ICONS_H */
